/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.*;
import org.sql2o.*;

public abstract class Animals {
   
   public String name;
   public int id;

   public String getName(){
   	return name;
   }

   public String getId(){
     return id;
   }

     @Override
  public boolean equals(Object otherAnimals){
    if (!(otherAnimals instanceof Animals)) {
      return false;
    } else {
      Animals newAnimals = (Animals) otherAnimals;
      return this.getName().equals(newAnimals.getName())&&
      this.getId()==(newAnimals.getId());

    }
  }



  public void delete() {
    try(Connection con = DB.sql2o.open()) {
    String sql = "DELETE FROM animals WHERE id = :id;";
    con.createQuery(sql)
      .addParameter("id", this.id)
      .executeUpdate();
    }
  }
  
  public  static List<Animals> all(){
  	try (Connection con = DB.sql2o.open()){
  		String sql = "SELECT * FROM animals";
      con.createQuery(sql)
      .executeAndFetch();

  	}

  	public static Animals find(int id){
  		try(Connection con =DB.sql2o.open()){
  			String sql = "SELECT * FROM animals WHERE id=:id"
  			Animals animal = con.createQuery(sql)
  			.addParameter("id",id)
  			.executeAndFetchFirst(Animals.class)
  			return animal;
  		}
  	}

  	public void update (String name){
  		try(Connection con = DB.sql2o.open()){
  		String sql ="UPDATE animals SET name=:name WHERE id=:id";
  			con.createQuery(sql)
  			.addParameter("id",id)
  			.addParameter("name",name)
  			.executeUpdate();
  		}
  	}

  	public  static List<Sightings> getSightings(){
       try(Connection con = DB.sql2o.open()){
       String sql ="SELECT * FROM Sightings WHERE animalId=:id";
       con.createQuery(sql)
       .addParameter("id",id)
       executeUpdate();
       }
  	}
  
}


